import configparser
import os

class ConfigLoader:
    def __init__(self,path):
        config = configparser.ConfigParser()
        config.read(path)
        self.is_train = config.getboolean('RunConfig','is_train')
        self.input_data_path = config.get('RunConfig','input_data_path')
        self.load_epoch = config.getint('RunConfig','load_epoch')
        self.train_path = config.get('RunConfig','train_path')
        self.det_threshold = config.getfloat('RunConfig','det_threshold')
        self.epoch = config.getint('RunConfig','epoch')
        self.img_begin_index = config.getint('RunConfig','img_begin_index')
        self.img_index_bits = config.getint('RunConfig','img_index_bits')
        self.img_cache_size = config.getint('RunConfig','img_cache_size')
        self.vgg16_npy_path = config.get('RunConfig','vgg16_npy_path')
        self.data_path = config.get('RunConfig','data_path')
        self.train_folder_name = config.get('RunConfig','train_folder_name')
        self.train_image_folder_name = config.get('RunConfig','train_image_folder_name')
        self.train_det_folder_name = config.get('RunConfig','train_det_folder_name')
        self.train_gt_folder_name = config.get('RunConfig','train_gt_folder_name')
        self.train_det_file_name = config.get('RunConfig','train_det_file_name')
        self.train_gt_file_name = config.get('RunConfig','train_gt_file_name')
        self.sequence_info_file_name = config.get('RunConfig','sequence_info_file_name')
        self.test_folder_name = config.get('RunConfig','test_folder_name')
        self.test_image_folder_name = config.get('RunConfig','test_image_folder_name')
        self.test_det_folder_name = config.get('RunConfig','test_det_folder_name')
        self.test_det_file_name = config.get('RunConfig','test_det_file_name')
        self.img_file_type = config.get('RunConfig','img_file_type')
        self.tracker_result_path = config.get('RunConfig','tracker_result_path')
        self.model_save_path = config.get('RunConfig','model_save_path')
        self.model_save_epoch = config.getint('RunConfig','model_save_epoch')
        self.gpu_index = config.getint('RunConfig','gpu_index')
        self.summary_log_save_path = config.get('RunConfig','summary_log_save_path')

        self.gru_keep_prob = config.getfloat('SuperConfig','gru_keep_prob')
        self.nn_keep_prob = config.getfloat('SuperConfig','nn_keep_prob')
        self.learn_rate = config.getfloat('SuperConfig','learn_rate')

        self.max_target_number = config.getint('NetConfig','max_target_number')
        self.gru_hide_size = config.getint('NetConfig','gru_hide_size')
        self.product_dim = config.getint('NetConfig','product_dim')
        self.sequence_size = config.getint('NetConfig','sequence_size')
        self.input_w_size = config.getint('NetConfig','input_w_size')
        self.input_h_size = config.getint('NetConfig','input_h_size')
        self.img_resize_w = config.getint('NetConfig','img_resize_w')
        self.img_resize_h = config.getint('NetConfig','img_resize_h')
        self.pic_feature_dim = config.getint('NetConfig','pic_feature_dim')
        self.det_feature_dim = config.getint('NetConfig','det_feature_dim')
        self.all_feature_dim = config.getint('NetConfig','all_feature_dim')
        self.det_dim = config.getint('NetConfig','det_dim')
        self.product_hidden_size = config.getint('NetConfig','product_hidden_size')
        self.fc_sec_hidden_size = config.getint('NetConfig','fc_sec_hidden_size')
        self.batch_size = config.getint('NetConfig','batch_size')
        self.test_loop_size = config.getint('NetConfig','test_loop_size')
        self.gru_larys = config.getint('NetConfig','gru_larys')